# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: video_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'video_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13video_service.proto\x12\x03\x64va\"\x07\n\x05\x45mpty\"O\n\x0eHealthResponse\x12\r\n\x05ready\x18\x01 \x01(\x08\x12\x12\n\nmodel_name\x18\x02 \x01(\t\x12\x1a\n\x12gpu_memory_used_mb\x18\x03 \x01(\x05\"\xc9\x01\n\x0ePredictRequest\x12\x16\n\x0e\x63ontext_frames\x18\x01 \x03(\x0c\x12\x1c\n\x14language_instruction\x18\x02 \x01(\t\x12%\n\x10previous_actions\x18\x03 \x03(\x0b\x32\x0b.dva.Action\x12\x19\n\x11num_output_frames\x18\x04 \x01(\x05\x12\x16\n\x0eguidance_scale\x18\x05 \x01(\x02\x12\x19\n\x11num_denoise_steps\x18\x06 \x01(\x05\x12\x0c\n\x04seed\x18\x07 \x01(\x05\"d\n\x06\x41\x63tion\x12\n\n\x02\x64x\x18\x01 \x01(\x02\x12\n\n\x02\x64y\x18\x02 \x01(\x02\x12\n\n\x02\x64z\x18\x03 \x01(\x02\x12\x0b\n\x03\x64rx\x18\x04 \x01(\x02\x12\x0b\n\x03\x64ry\x18\x05 \x01(\x02\x12\x0b\n\x03\x64rz\x18\x06 \x01(\x02\x12\x0f\n\x07gripper\x18\x07 \x01(\x02\"F\n\x0fPredictResponse\x12\x18\n\x10generated_frames\x18\x01 \x03(\x0c\x12\x19\n\x11inference_time_ms\x18\x02 \x01(\x02\"3\n\rFrameResponse\x12\r\n\x05\x66rame\x18\x01 \x01(\x0c\x12\x13\n\x0b\x66rame_index\x18\x02 \x01(\x05\x32\xc0\x01\n\x12\x43osmosVideoService\x12\x39\n\x0cPredictVideo\x12\x13.dva.PredictRequest\x1a\x14.dva.PredictResponse\x12?\n\x12PredictVideoStream\x12\x13.dva.PredictRequest\x1a\x12.dva.FrameResponse0\x01\x12.\n\x0bHealthCheck\x12\n.dva.Empty\x1a\x13.dva.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'video_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=28
  _globals['_EMPTY']._serialized_end=35
  _globals['_HEALTHRESPONSE']._serialized_start=37
  _globals['_HEALTHRESPONSE']._serialized_end=116
  _globals['_PREDICTREQUEST']._serialized_start=119
  _globals['_PREDICTREQUEST']._serialized_end=320
  _globals['_ACTION']._serialized_start=322
  _globals['_ACTION']._serialized_end=422
  _globals['_PREDICTRESPONSE']._serialized_start=424
  _globals['_PREDICTRESPONSE']._serialized_end=494
  _globals['_FRAMERESPONSE']._serialized_start=496
  _globals['_FRAMERESPONSE']._serialized_end=547
  _globals['_COSMOSVIDEOSERVICE']._serialized_start=550
  _globals['_COSMOSVIDEOSERVICE']._serialized_end=742
# @@protoc_insertion_point(module_scope)
