# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import video_service_pb2 as video__service__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in video_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CosmosVideoServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PredictVideo = channel.unary_unary(
                '/dva.CosmosVideoService/PredictVideo',
                request_serializer=video__service__pb2.PredictRequest.SerializeToString,
                response_deserializer=video__service__pb2.PredictResponse.FromString,
                _registered_method=True)
        self.PredictVideoStream = channel.unary_stream(
                '/dva.CosmosVideoService/PredictVideoStream',
                request_serializer=video__service__pb2.PredictRequest.SerializeToString,
                response_deserializer=video__service__pb2.FrameResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/dva.CosmosVideoService/HealthCheck',
                request_serializer=video__service__pb2.Empty.SerializeToString,
                response_deserializer=video__service__pb2.HealthResponse.FromString,
                _registered_method=True)


class CosmosVideoServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PredictVideo(self, request, context):
        """Single chunk prediction
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PredictVideoStream(self, request, context):
        """Streaming prediction for Leapfrog
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CosmosVideoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PredictVideo': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictVideo,
                    request_deserializer=video__service__pb2.PredictRequest.FromString,
                    response_serializer=video__service__pb2.PredictResponse.SerializeToString,
            ),
            'PredictVideoStream': grpc.unary_stream_rpc_method_handler(
                    servicer.PredictVideoStream,
                    request_deserializer=video__service__pb2.PredictRequest.FromString,
                    response_serializer=video__service__pb2.FrameResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=video__service__pb2.Empty.FromString,
                    response_serializer=video__service__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dva.CosmosVideoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dva.CosmosVideoService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CosmosVideoService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PredictVideo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dva.CosmosVideoService/PredictVideo',
            video__service__pb2.PredictRequest.SerializeToString,
            video__service__pb2.PredictResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PredictVideoStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/dva.CosmosVideoService/PredictVideoStream',
            video__service__pb2.PredictRequest.SerializeToString,
            video__service__pb2.FrameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dva.CosmosVideoService/HealthCheck',
            video__service__pb2.Empty.SerializeToString,
            video__service__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
